var CHEMO_CONSTANTS = {
	timeStepHours: 2,
	defaultDurationHours: 720,
	visualChannels: [
		{ key: "bloodstream", label: "Bloodstream", color: "#d65050" },
		{ key: "liver", label: "Liver", color: "#dd8b3d" },
		{ key: "kidney", label: "Kidneys", color: "#4a7db2" },
		{ key: "tumor", label: "Tumor", color: "#7e5bd6" },
	],
	organInfo: [
		{ key: "bloodstream", label: "Bloodstream", role: "Carries the drug rapidly through the body right after dosing." },
		{ key: "liver", label: "Liver", role: "Breaks down and processes much of the chemotherapy burden." },
		{ key: "kidney", label: "Kidneys", role: "Clear water-soluble drug and metabolites from circulation." },
		{ key: "tumor", label: "Tumor", role: "Receives exposure that can reduce tumor mass over time." },
	],
	drugs: {
		doxorubicin: {
			id: "doxorubicin",
			name: "Doxorubicin",
			color: "#a63446",
			infusionHours: 1,
			centralVolumeLiters: 24,
			peripheralVolumeLiters: 32,
			eliminationHalfLifeHours: 30,
			distributionHalfLifeHours: 4,
			bodyAffinity: { bloodstream: 1.2, liver: 0.9, kidney: 0.4, tumor: 1.0 },
		},
		bleomycin: {
			id: "bleomycin",
			name: "Bleomycin",
			color: "#2b7a78",
			infusionHours: 0.75,
			centralVolumeLiters: 20,
			peripheralVolumeLiters: 18,
			eliminationHalfLifeHours: 8,
			distributionHalfLifeHours: 2,
			bodyAffinity: { bloodstream: 1.0, liver: 0.5, kidney: 1.1, tumor: 0.8 },
		},
		vinblastine: {
			id: "vinblastine",
			name: "Vinblastine",
			color: "#8a5cf5",
			infusionHours: 0.5,
			centralVolumeLiters: 18,
			peripheralVolumeLiters: 22,
			eliminationHalfLifeHours: 24,
			distributionHalfLifeHours: 3,
			bodyAffinity: { bloodstream: 0.9, liver: 0.6, kidney: 0.4, tumor: 1.15 },
		},
		dacarbazine: {
			id: "dacarbazine",
			name: "Dacarbazine",
			color: "#ef8d32",
			infusionHours: 1.5,
			centralVolumeLiters: 26,
			peripheralVolumeLiters: 26,
			eliminationHalfLifeHours: 5,
			distributionHalfLifeHours: 1.5,
			bodyAffinity: { bloodstream: 1.1, liver: 0.8, kidney: 0.9, tumor: 0.7 },
		},
		oxaliplatin: {
			id: "oxaliplatin",
			name: "Oxaliplatin",
			color: "#3566c6",
			infusionHours: 2,
			centralVolumeLiters: 18,
			peripheralVolumeLiters: 28,
			eliminationHalfLifeHours: 18,
			distributionHalfLifeHours: 3,
			bodyAffinity: { bloodstream: 1.0, liver: 0.7, kidney: 0.8, tumor: 0.95 },
		},
		leucovorin: {
			id: "leucovorin",
			name: "Leucovorin",
			color: "#5ba36e",
			infusionHours: 2,
			centralVolumeLiters: 22,
			peripheralVolumeLiters: 20,
			eliminationHalfLifeHours: 6,
			distributionHalfLifeHours: 1.5,
			bodyAffinity: { bloodstream: 0.85, liver: 0.6, kidney: 0.7, tumor: 0.6 },
		},
		fluorouracil: {
			id: "fluorouracil",
			name: "5-Fluorouracil",
			color: "#cc5c91",
			infusionHours: 46,
			centralVolumeLiters: 16,
			peripheralVolumeLiters: 14,
			eliminationHalfLifeHours: 10,
			distributionHalfLifeHours: 2.5,
			bodyAffinity: { bloodstream: 1.25, liver: 0.55, kidney: 0.5, tumor: 1.2 },
		},
	},
	regimens: [
		{
			id: "abvd",
			name: "ABVD",
			subtitle: "Hodgkin lymphoma teaching preset",
			cycleHours: 336,
			drugIds: ["doxorubicin", "bleomycin", "vinblastine", "dacarbazine"],
			teachingNotes: [
				"Multiple agents are introduced early, so the combined concentration burden spikes quickly.",
				"Bleomycin clears faster than doxorubicin, which makes late-cycle exposure profiles diverge.",
				"The tumor channel stays elevated longer when tissue affinity is high, even as bloodstream levels fall.",
			],
			warning: "Illustrative ABVD timing only. The values are generalized for teaching trends.",
			doseEvents: [
				{ id: "abvd-1", drugId: "doxorubicin", label: "Day 1 Doxorubicin", startHour: 0, durationHours: 1, amountMg: 42 },
				{ id: "abvd-2", drugId: "bleomycin", label: "Day 1 Bleomycin", startHour: 0, durationHours: 0.75, amountMg: 16 },
				{ id: "abvd-3", drugId: "vinblastine", label: "Day 1 Vinblastine", startHour: 1, durationHours: 0.5, amountMg: 10 },
				{ id: "abvd-4", drugId: "dacarbazine", label: "Day 1 Dacarbazine", startHour: 1, durationHours: 1.5, amountMg: 640 },
				{ id: "abvd-5", drugId: "doxorubicin", label: "Day 15 Doxorubicin", startHour: 168, durationHours: 1, amountMg: 42 },
				{ id: "abvd-6", drugId: "bleomycin", label: "Day 15 Bleomycin", startHour: 168, durationHours: 0.75, amountMg: 16 },
				{ id: "abvd-7", drugId: "vinblastine", label: "Day 15 Vinblastine", startHour: 169, durationHours: 0.5, amountMg: 10 },
				{ id: "abvd-8", drugId: "dacarbazine", label: "Day 15 Dacarbazine", startHour: 169, durationHours: 1.5, amountMg: 640 },
			],
		},
		{
			id: "folfox",
			name: "FOLFOX",
			subtitle: "Colorectal cancer teaching preset",
			cycleHours: 336,
			drugIds: ["oxaliplatin", "leucovorin", "fluorouracil"],
			teachingNotes: [
				"Oxaliplatin peaks early, while 5-fluorouracil contributes a long tail because of the extended infusion.",
				"Leucovorin changes the combined exposure mix without dominating total burden.",
				"Long infusion windows flatten the curve and sustain tumor exposure longer than a short bolus alone.",
			],
			warning: "Illustrative FOLFOX timing only. The values are generalized for teaching trends.",
			doseEvents: [
				{ id: "folfox-1", drugId: "oxaliplatin", label: "Day 1 Oxaliplatin", startHour: 0, durationHours: 2, amountMg: 180 },
				{ id: "folfox-2", drugId: "leucovorin", label: "Day 1 Leucovorin", startHour: 0, durationHours: 2, amountMg: 400 },
				{ id: "folfox-3", drugId: "fluorouracil", label: "5-FU Bolus", startHour: 2, durationHours: 0.25, amountMg: 450 },
				{ id: "folfox-4", drugId: "fluorouracil", label: "5-FU Infusion", startHour: 2.25, durationHours: 46, amountMg: 2600 },
			],
		},
	],
};
